Repository Nuclear-Squid/ergol, pull requests merged in 2024-03, with the labels that each got.

#99 Draft: lexique
  www/content/lexique.md
  www/content/stats.html
Labels: documentation

#118 SVG geometry selector & theme refinements
  code/keebs.js
  www/assets/css/keebs.css
  www/assets/css/theme.css
  www/content/_index.md
  www/content/bepo/index.md
  www/content/dactylo/index.html
  www/content/erglace.md
  www/content/lafayette.md
  www/content/stats.html
  www/layouts/shortcodes/x-keyboard.html
  www/static/img/bepo.svg
  www/static/img/bepolar.svg
  www/static/img/colemak-french-touch.svg
  www/static/img/erglace.svg
  www/static/img/ergol.svg
  www/static/img/ergol_1dfh.svg
  www/static/img/lafayette.svg
Labels: enhancement

#119 OpenGraph metadata
  www/layouts/partials/head.html
  www/static/ergol.png
  www/static/img/ergol.png
  www/static/img/index.html
Labels: enhancement

#123 better mobile layout
  www/assets/css/keebs.css
  www/assets/css/theme.css
  www/content/dactylo/index.html
  www/content/lexique.md
  www/layouts/shortcodes/x-keyboard.html
Labels: bug

#138 [lts] fix wrong URL
  www/content/lts/index.md
Labels: bug

#137 x-keyboard: Improve buttons
  www/assets/css/keebs.css
  www/layouts/shortcodes/x-keyboard.html
Labels: enhancement

#150 [www] better submenu
  www/assets/css/theme.css
Labels: enhancement

#147 [www] articles & authors
  www/assets/css/theme.css
  www/content/_index.md
  www/content/alternatives/index.md
  www/content/alternatives/optimot_en.png
  www/content/alternatives/optimot_fr.png
  www/content/articles/bienvenue.md
  www/content/presentation/ergol_1dfh.svg
  www/content/presentation/ergol_1dk.svg
  www/content/presentation/ergol_1dk_de.svg
  www/content/presentation/ergol_altgr.svg
  www/content/presentation/ergol_en.svg
  www/content/presentation/ergol_fr.svg
  www/content/presentation/index.md
  www/data/authors/kaze.toml
  www/data/authors/nuclear_squid.toml
  www/hugo.toml
  www/layouts/_default/home.html
  www/layouts/_default/list.html
  www/layouts/_default/single.html
  www/layouts/partials/head.html
Labels: enhancement

#148 feat(website): new word definitions in the glossary
  www/content/lexique.md
Labels: documentation
